from io import BytesIO
from django.http import HttpResponse
from django.core.mail import EmailMessage
from django.conf import settings
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

# Try to use real models if they exist
try:
    from .models import Invoice, InvoiceLine  # type: ignore
except Exception:
    Invoice = None
    InvoiceLine = None

def _make_pdf(invoice_id: int, title='Invoice'):
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    c.setTitle(f"{title} #{invoice_id}")
    c.setFont('Helvetica-Bold', 18)
    c.drawString(72, 800, f"{title} #{invoice_id}")
    c.setFont('Helvetica', 11)
    c.drawString(72, 780, "This PDF is generated by BizSuite (dev).")
    c.drawString(72, 760, "If your Invoice model exists, wire real data later.")
    c.showPage()
    c.save()
    return buf.getvalue()

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def invoices_list(request):
    if Invoice:
        items = []
        try:
            qs = Invoice.objects.all().order_by('-id')[:50]
            for inv in qs:
                number = getattr(inv, 'number', getattr(inv, 'name', str(inv.pk)))
                date   = getattr(inv, 'date', None)
                total  = getattr(inv, 'total', None)
                # compute a total if field missing and InvoiceLine exists
                if total is None and InvoiceLine:
                    try:
                        lines = InvoiceLine.objects.filter(invoice=inv)
                        tot = 0.0
                        for ln in lines:
                            qty  = float(getattr(ln, 'quantity', 1) or 1)
                            unit = float(getattr(ln, 'unit_price', 0) or 0)
                            tot += qty*unit
                        total = tot
                    except Exception:
                        pass
                items.append({
                    'id': inv.pk,
                    'number': str(number),
                    'date': str(date) if date else None,
                    'total': float(total) if isinstance(total, (int,float)) else None
                })
            return Response({'count': len(items), 'results': items})
        except Exception as e:
            # Fall through to demo data on error
            pass

    # Demo data when models unavailable
    return Response({
        'count': 3,
        'results': [
            {'id': 1, 'number': 'INV-001', 'date': '2025-01-05', 'total': 100.0},
            {'id': 2, 'number': 'INV-002', 'date': '2025-02-10', 'total': 250.0},
            {'id': 3, 'number': 'INV-003', 'date': '2025-03-20', 'total': 75.5},
        ]
    })

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def invoice_pdf(request, pk: int):
    try:
        pdf = _make_pdf(pk)
        resp = HttpResponse(pdf, content_type='application/pdf')
        resp['Content-Disposition'] = f'inline; filename="invoice_{pk}.pdf"'
        return resp
    except Exception as e:
        return Response({'ok': False, 'error': str(e)}, status=500)

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def invoice_email(request, pk: int):
    try:
        to = request.data.get('to') or 'test@inbox.local'
        subject = request.data.get('subject') or f'Invoice #{pk} – Test'
        message = request.data.get('message') or 'Attached invoice PDF.'
        pdf = _make_pdf(pk)
        msg = EmailMessage(subject, message, settings.DEFAULT_FROM_EMAIL, [to])
        msg.attach(f'invoice_{pk}.pdf', pdf, 'application/pdf')
        sent = msg.send()
        return Response({'status': 'sent' if sent else 'queued', 'to': to})
    except Exception as e:
        return Response({'ok': False, 'error': str(e)}, status=500)